language: java

services:
  - docker

before_install:
  - docker pull alvrme/alpine-android:android-29
  - docker run -it -d --name test alvrme/alpine-android:android-29 bash
  - docker cp . test:/home/android
  
install: true

before_script:
  - docker exec test echo "org.gradle.daemon=false" >> gradle.properties
  - docker exec test echo "org.gradle.parallel=true" >> gradle.properties
  - docker exec test touch droidconKE.jks
  - docker exec test chmod +x ./gradlew

script: docker exec test ./gradlew -Pci --console=plain testDebug
